language: csharp
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh
  - source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade
script:
  - ./build.sh
mono:
  - nightly
notifications:
  email: false
